### ISSUE TITLE
Embed URL points to localhost with allinone image

### ISSUE THREAD

**Issue by jojoob** [opencast/opencast-docker#153]
I've an opencast configuration problem with the allinone docker image. For some reason "localhost:8080" is used by Opencast for the video embed code and maybe on other places too. Below is a snipped of my docker-compose file.
The only way I've found to tell Opencast to use the server IP address is to modify `org.opencastproject.organization-mh_default_org.cfgorg.opencastproject.organization-mh_default_org.cfg`. Even though the comments in the file state that `${org.opencastproject.server.url}` is the default value.

```yaml
opencast:
  image: quay.io/opencast/allinone:9.2
  environment:
    ORG_OPENCASTPROJECT_SERVER_URL: http://{{ip}}:8080
    ORG_OPENCASTPROJECT_DOWNLOAD_URL: http://{{ip}}:8080/static
    PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL: http://{{ip}}:8080
    PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL: http://{{ip}}:8080
    ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER: {{adminuser}}
    ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS: {{adminpass}}
    ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER: {{digestuser}}
    ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS: {{digestpass}}
    ORG_OPENCASTPROJECT_DB_VENDOR: MariaDB
    ORG_OPENCASTPROJECT_DB_JDBC_URL: jdbc:mysql://mariadb/{{dbname}}?useMysqlMetadata=true
    ORG_OPENCASTPROJECT_DB_JDBC_USER: {{dbuser}}
    ORG_OPENCASTPROJECT_DB_JDBC_PASS: {{dbpass}}
    ACTIVEMQ_BROKER_URL: failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectDelay=60000
    ACTIVEMQ_BROKER_USERNAME: {{activemquser}}
    ACTIVEMQ_BROKER_PASSWORD: {{activemqpass}}
    ELASTICSEARCH_SERVER_HOST: elasticsearch
  volumes:
    - data:/data
  ports:
    - 8080:8080
```

I also tested a "distributed" setup on a single docker host and the problem did not occur.
A short test with a direct install of the allinone package on Ubuntu brought the same problem as described above. So maybe this is not related to the docker image and I should post this on the main opencast project...
